#########################
## Sample Sass Lint File
#########################
# Rule Configuration
rules:
  indentation:
    - 2
    -
      size: 2
  class-name-format:
    - 0
  mixin-name-format: 
    - 0
  variable-name-format: 
    - 0
  no-vendor-prefix:
    - 1
    -
      'excluded-identifiers':
        - 'webkit'
  hex-notation:
    - 0
  hex-length:
    - 1
    - 
      style: long
  border-zero:
    - 1
    -
      convention: 'none'
  leading-zero:
    - 1
    -
      include: true
  no-misspelled-properties:
  - 1
  -
    'extra-properties':
      - '-webkit-overflow-scrolling'