#!/bin/sh

NOW=$(date +"%s")
NAME=social-helper-database-$NOW.sql
BACKUP_DIR=$PWD/backups
FILE_PATH=$BACKUP_DIR/$NAME

mkdir -p $BACKUP_DIR

docker exec social-helper-db sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > `echo $FILE_PATH`
