FROM node:boron

# Create app directory
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/web
WORKDIR /usr/src/app/web

# Install app dependencies
COPY web/package.json /usr/src/app/web
RUN npm install

# Bundle app source
COPY web /usr/src/app/web
COPY .env /usr/src/app

EXPOSE 3000
CMD [ "npm", "run", "gulp", "watch" ]
